updated files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,5 +58,7 @@ jobs:
           export PATH=\$PATH:/root/dev_ws/install/my_robot_controller/bin && \
           echo 'Rechecking PATH variable...'
           echo \$PATH && \
+          echo 'Trying to run move_robot manually...'
+          /root/dev_ws/install/my_robot_controller/bin/move_robot || echo 'ERROR: move_robot failed manually' && \          
           echo 'Running move_robot node...'
           ros2 run my_robot_controller move_robot || echo 'ERROR: move_robot failed to execute'"
