updated files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,18 +32,9 @@ jobs:
 
   test-container:
     needs: build-and-push
-    # runs-on: ubuntu-24.04  # Consistently use Ubuntu 24.04 here too for testing
     runs-on: ubuntu-latest  # Ensure Docker is available by default
 
     steps:
-      # - name: Install Docker Manually (Fix Unmet Dependencies)
-      #   run: |
-      #     sudo apt-get update
-      #     curl -fsSL https://get.docker.com | sudo sh
-      #     sudo systemctl start docker
-      #     sudo systemctl enable docker
-      #     sudo usermod -aG docker $USER
-
       - name: Pull and Run the Docker Container
         run: |
           docker pull tangbr/project1_ros2:latest
@@ -70,5 +61,5 @@ jobs:
           echo \$PATH && \
           echo 'Trying to run move_robot manually...'
           /root/dev_ws/install/my_robot_controller/bin/move_robot || echo 'ERROR: move_robot failed manually' && \          
-          echo 'Running move_robot node...'
-          ros2 run my_robot_controller move_robot || echo 'ERROR: move_robot failed to execute'"
+          echo 'Running move_robot node (with timeout)...'          
+          timeout 5s ros2 run my_robot_controller move_robot || echo 'ERROR: move_robot failed to execute'"
